import express from 'express';
import { requireSignIn } from '../middleware/authmiddleware.js';
import { forgotpasswordcontroller, loginController, mailcontroller, registerController, verifyotpcontroller, getpasswordcontroller,changepasswordcontroller, verifychangepasswordcontroller, contactcontroller } from '../controllers/authcontroller.js';
const router=express.Router();
router.post("/register",registerController);
router.post("/login",loginController);
router.post("/sendotp",mailcontroller);
router.post("/verifyotp",verifyotpcontroller);
router.post("/forgotpassword",requireSignIn,forgotpasswordcontroller);
router.post("/recievepassword/:success",requireSignIn,getpasswordcontroller);
router.post("/changepassword",requireSignIn,changepasswordcontroller);
router.post("/verifychangepassword/:success",requireSignIn,verifychangepasswordcontroller);
router.post("/contact",requireSignIn,contactcontroller);
export default router;